name: Build and Sign
on:
  push:
    branches:
      - main
      - pre

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Nuitka and dependencies
        run: |
          pip install Nuitka
          pip install -r requirements.txt

      - name: Build with Nuitka
        run: python -m nuitka --standalone --enable-plugin=tk-inter --output-dir="build" --output-filename="ScryptTunes.exe" .\main.py

      - name: Install NSIS
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          scoop update
          scoop bucket add extras
          scoop install nsis

      - name: Create Installer
        run: makensis installer.nsi

      - name: Code sign a file
        uses: dlemstra/code-sign-action@v1
        with:
          certificate: '${{ secrets.SIGNING_KEY }}'
          password: '${{ secrets.CERT_PASSWORD }}'
          files: './build/ScryptTunesInstaller.exe'

      - name: Get version from file
        id: version
        run: |
          $version = Get-Content -Path VERSION -Raw
          echo "::set-output name=version::$version"

      - name: Release for main branch
        if: github.ref == 'refs/heads/main'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./build/ScryptTunesInstaller.exe"
          skipIfReleaseExists: True
          tag: ${{ steps.version.outputs.version }}
          makeLatest: true

      - name: Release for pre branch
        if: github.ref == 'refs/heads/pre'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./build/ScryptTunesInstaller.exe"
          skipIfReleaseExists: True
          tag: pre-${{ steps.version.outputs.version }}
          prerelease: true

