name: Build and Sign
on:
  push:
    branches:
      - gh-actions-test
    
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.0

    - name: Build with PyInstaller
      uses: sayyid5416/pyinstaller@v1
      with:
        spec: main.py
        requirements: requirements.txt
        options: --onefile, --noconsole

    - name: Code sign a file
      uses: dlemstra/code-sign-action@v1
      with:
        certificate: '${{ secrets.SIGNING_KEY }}'
        password: '${{ secrets.CERT_PASSWORD }}'
        files:
          './dist/main.exe'

    - name: Rename Artifact
      run: mv ./dist/main.exe ./dist/ScryptTunes.exe

    - name: Create Release
      id: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Get latest release version
        $latestVersion = gh release list --json version --limit 1 | ConvertFrom-Json | Select-Object -ExpandProperty version

        # Increment version
        $versionArray = $latestVersion.Split(".")
        $versionArray[-1] = [int]$versionArray[-1] + 1
        $nextVersion = $versionArray -join "."
        Write-Host "Next version is $nextVersion"

        # Create release
        $releaseId = gh release create $nextVersion ./dist/ScryptTunes.exe -d -t "Release $nextVersion" --json id | ConvertFrom-Json | Select-Object -ExpandProperty id
        Write-Host "Created release with ID $releaseId"

        # Set release ID for next step
        echo "release_id=$releaseId" | Out-File -FilePath $env:GITHUB_ENV -Append
        
    # - name: Upload Artifact
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run:
    #     gh release upload ${{ steps.release.outputs.id }} ./dist/ScryptTunes.py

