name: Build and Sign
on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.0

    - name: Build with PyInstaller
      uses: sayyid5416/pyinstaller@v1
      with:
        spec: main.py
        requirements: requirements.txt
        options: --onefile, --noconsole

    - name: Code sign a file
      uses: dlemstra/code-sign-action@v1
      with:
        certificate: '${{ secrets.SIGNING_KEY }}'
        password: '${{ secrets.CERT_PASSWORD }}'
        files:
          './dist/main.exe'

    - name: Rename Artifact
      run: mv ./dist/main.exe ./dist/ScryptTunes.exe

    - name: Get version from file
      id: version
      run: |
        $version = Get-Content -Path VERSION -Raw
        echo "::set-output name=version::$version"

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "./dist/ScryptTunes.exe"
        skipIfReleaseExists: True
        tag: ${{ steps.version.outputs.version }}
        
      
        
    # - name: Upload Artifact
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run:
    #     gh release upload ${{ steps.release.outputs.id }} ./dist/ScryptTunes.py

